# Generated by Django 3.0.3 on 2020-03-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mydb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=100)),
                ('user_select', models.CharField(max_length=100)),
                ('user_area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mydb1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.CharField(max_length=100)),
            ],
        ),
    ]
