# Generated by Django 2.2.10 on 2020-03-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_mydb_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydb',
            name='user_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
