# Generated by Django 2.2.10 on 2020-03-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0004_auto_20200301_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydb',
            name='user_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
