# Generated by Django 2.2.10 on 2020-03-01 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0005_auto_20200301_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydb',
            name='user_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
