# Generated by Django 2.2.10 on 2020-03-01 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0006_auto_20200301_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydb',
            name='user_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
